# Generated by Django 4.1.2 on 2022-11-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_regstr', '0002_alter_position_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
