# Generated by Django 4.1.2 on 2022-11-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_regstr', '0003_rename_fullname_employee_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='Place',
        ),
    ]
