# Generated by Django 4.1.2 on 2022-11-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_regstr', '0004_rename_position_place_rename_position_employee_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
