# Generated by Django 4.1.2 on 2022-11-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_regstr', '0005_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
