# Generated by Django 4.1.2 on 2022-11-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_regstr', '0007_alter_employee_place_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Place',
        ),
    ]
