# Generated by Django 4.1.2 on 2022-11-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_regstr', '0008_delete_place_remove_employee_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
